version: '3.4'
services:
  web-server:
    container_name: webserver
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./build/web-server/default.conf:/etc/nginx/conf.d/default.conf
  api-server:
    build:
      context: .
      dockerfile: ./build/APIserver/prod/Dockerfile
    container_name: api-server
    restart: always
    depends_on:
      - redis
    tty: true
    volumes:
      - "./APIserver/:/app"
  bff:
    build:
      context: .
      dockerfile: ./build/BFF/prod/Dockerfile
    container_name: bff
    restart: always
    volumes:
      - "./BFF/:/app"

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - "./build/redis/data:/data"
