"""
    Haique

    HaiqueのもろもろのAPI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_haiku(self):
        """Test case for delete_haiku

        """
        pass

    def test_delete_subscribe(self):
        """Test case for delete_subscribe

        """
        pass

    def test_get_haiku(self):
        """Test case for get_haiku

        get_haiku  # noqa: E501
        """
        pass

    def test_get_timeline(self):
        """Test case for get_timeline

        timeline  # noqa: E501
        """
        pass

    def test_get_top(self):
        """Test case for get_top

        top  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        user_info  # noqa: E501
        """
        pass

    def test_post_haiku(self):
        """Test case for post_haiku

        """
        pass

    def test_post_signin(self):
        """Test case for post_signin

        """
        pass

    def test_post_signup(self):
        """Test case for post_signup

        """
        pass

    def test_post_subscribe(self):
        """Test case for post_subscribe

        """
        pass


if __name__ == '__main__':
    unittest.main()
