"""
    Haique

    HaiqueのもろもろのAPI  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.haiku_content import HaikuContent


class TestHaikuContent(unittest.TestCase):
    """HaikuContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHaikuContent(self):
        """Test HaikuContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HaikuContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
